### ISSUE TITLE
1.3 Edit habit

### ISSUE THREAD

**Issue by YulingShen** [CMPUT301F21T14/HAVE_IT#11]
As a user, I can edit the details of a habit of mine

US 01.04.01
	
Completion Requirements:
--In the same activity for viewing the details of habit, we could edit the details of the activity
--User should not be able to edit one habit title to the same title as another habit. (Such as we have habit a&b, we couldn't change the title of b to a, since a is already exits)
--Since we create the document of habits based on habit title in firebase. So when the title is changing, all the contents (including its events) from the old habit should be fully transferred to the new habit. And the old habit will be deleted.

Story point: 4
Priority: 5
Risk: 3
Midpoint: yes

Done by Ruiqing Tian

**Comment by allenhonggod** [comment]
The add functionality was done by ShenYuLing and tested by Wenzhuo Hong
