### ISSUE TITLE
1.6 List of all habits

### ISSUE THREAD

**Issue by Jasonchen-66** [CMPUT301F21T14/HAVE_IT#14]
As user, I can view a list of all habits

US 01.08.01

Completion Requirements:
-UI:This is a listview in the habit page with all habits in it
-User may be able to click on any item of it to view full detail of the habit

Story point: 1
Priority: 2
Risk: 1
Midpoint: yes

Done by Yuling Shen

Tested by Hongwen Zhuo

**Comment by allenhonggod** [comment]
The method was implemented by ShenYuling and the test was done by Wenzhuo Hong.
