### ISSUE TITLE
2.4 Edit Habit Event

### ISSUE THREAD

**Issue by Yrviocnhnie** [CMPUT301F21T14/HAVE_IT#21]
As a user, I can edit the details of a habit event of mine

US 02.05.01
Completion Requirements:
-UI: On the edit/delete page the event information: event and the date are shown. 
-User may be able to change its date and the event.

Story point: 4
Priority: 9
Risk: 3
Midpoint: yes

Done by Songkun Guo

**Comment by allenhonggod** [comment]
The functionality was implemented by RuiqingTian and was Tested by Wenzhuo Hong
