### ISSUE TITLE
2.5 Delete Habit Event

### ISSUE THREAD

**Issue by Yrviocnhnie** [CMPUT301F21T14/HAVE_IT#23]
As a user, I can delete a habit event of mine

US 02.06.01
Completion Requirements:
-UI: On the edit/delete page the event information: event and the date are shown. 
-User may be able to delete the event. However, the habit is relative to it not change. 

Story point: 2
Priority: 8
Risk: 3
Midpoint: yes

Done by Songkun Guo

**Comment by allenhonggod** [comment]
The method was completed by RuiqingTian and tested by Wenzhuo Hong
